version: "3.9"
services:
  back:
    depends_on:
      - db
    build:
      dockerfile: dev.Dockerfile
    ports:
      - "8080:8080"
    environment:
      MONGO_USERNAME: admin
      MONGO_PASSWORD: password
      MONGO_DATABASE: kitten
  db:
    image: mongo:latest
    environment:
      MONGO_INITDB_ROOT_USERNAME: admin
      MONGO_INITDB_ROOT_PASSWORD: password
    ports:
      - "27017:27017"