version: "3.3"
services:
  back:
    depends_on:
      - mongodb
    build:
      dockerfile: ${CI_COMMIT_REF_NAME:-dev}.Dockerfile
    ports:
      - "${CI_HOST}:8080"
  mongodb:
    hostname: db
    image: mongo:latest
    ports:
      - "27017:27017"